[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "16"

# Static export के लिए redirects और headers
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
